# Generated by Django 3.0.6 on 2020-05-14 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='логин')),
                ('first_name', models.CharField(max_length=50, verbose_name='имя')),
                ('middle_name', models.CharField(max_length=50, verbose_name='отчество')),
                ('last_name', models.CharField(max_length=50, verbose_name='фамилия')),
                ('is_dismissal', models.BooleanField()),
                ('date_dismissal', models.DateField(verbose_name='дата увольнения')),
                ('dismissal_order', models.CharField(max_length=50, verbose_name='приказ об увольнении')),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'сотрудники',
                'ordering': ['last_name', 'first_name', 'middle_name'],
            },
        ),
        migrations.CreateModel(
            name='VacationReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='начало отпуска')),
                ('end_date', models.DateField(verbose_name='конец отпуска')),
                ('description', models.CharField(max_length=100, verbose_name='основание')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='начало отпуска')),
                ('end_date', models.DateField(verbose_name='конец отпуска')),
                ('description', models.CharField(max_length=100, verbose_name='основание')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.Employee')),
            ],
        ),
    ]
