# Generated by Django 3.0.6 on 2020-05-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacation',
            options={'verbose_name': 'отпуск', 'verbose_name_plural': 'отпуска'},
        ),
        migrations.AlterModelOptions(
            name='vacationreview',
            options={'verbose_name': 'отзыв', 'verbose_name_plural': 'отзывы'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_dismissal',
            field=models.DateField(null=True, verbose_name='дата увольнения'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dismissal_order',
            field=models.CharField(max_length=50, null=True, verbose_name='приказ об увольнении'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_dismissal',
            field=models.BooleanField(verbose_name='уволен?'),
        ),
    ]
