# Generated by Django 3.0.6 on 2020-05-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_auto_20200514_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_dismissal',
            field=models.DateField(blank=True, null=True, verbose_name='дата увольнения'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dismissal_order',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='приказ об увольнении'),
        ),
    ]
