# Generated by Django 3.0.6 on 2020-05-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_auto_20200515_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.SlugField(unique=True, verbose_name='логин'),
        ),
    ]
